config/routes.rb
Rails.application.routes.draw do
  resources :courses
  
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"} , path: "accounts"
  
  scope controller: :static_pages do
    get :about
    get :contact
    get :index
    get :privacy
    get :course
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#index"
end

app/views/layouts/_flash_message.html.haml
#flash-message{:class => "alert #{flash_class(message_type.to_sym)}"}
  .fixed.inset-0.mt-16.flex.px-4.py-6.pointer-events-none.sm:p-6.sm:items-start.z-50{"aria-live" => "assertive"}
    .w-full.flex.flex-col.items-center.space-y-4.sm:items-end
      .max-w-sm.w-full.bg-white.shadow-lg.rounded-lg.pointer-events-auto.ring-1.ring-black.ring-opacity-5.overflow-hidden{data: {controller: "alert"}}
        .p-4
          .flex.items-start
            .flex-shrink-0
              .flash-icon{class: "#{flash_class(message_type.to_sym)}"}
                = svg("#{severity_icon(message_type.to_sym)}")
                
            .ml-3.w-0.flex-1{class: "pt-0.5"}
              %p.alert-message 
                = "#{message}"
 
            .ml-4.flex-shrink-0.flex
              %button.bg-white.rounded-md.inline-flex.text-gray-600.hover:text-gray-500.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-indigo-800{data: {action: "alert#close"}}
                %span.sr-only Close
                / Heroicon name: solid/x
                %svg.h-5.w-5{"aria-hidden" => "true", fill: "currentColor", viewbox: "0 0 20 20", xmlns: "http://www.w3.org/2000/svg"}
                  %path{"clip-rule" => "evenodd", d: "M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z", "fill-rule" => "evenodd"}
  = javascript_include_tag 'flash_timeout', async: true

app/views/layouts/_flash_messages.html.haml
.flash-messages

  - flash.each do |message_type, message|
    = render partial: "layouts/flash_message", locals: {message_type: message_type, message: message}
    

app/views/layouts/_header_nav.html.haml
/ This example requires Tailwind CSS v2.0+
%nav.bg-cyan-700{"data-controller" => "dropdown"}
  .max-w-7xl.mx-auto.px-2.sm:px-6.lg:px-20
    .relative.flex.items-center.justify-between.h-16
      .absolute.inset-y-0.left-0.flex.items-center.sm:hidden
        / Mobile menu button
        %button.inline-flex.items-center.justify-center.p-2.rounded-md.text-gray-400.hover:text-white.hover:bg-gray-700.focus:outline-none.focus:ring-2.focus:ring-inset.focus:ring-white{"aria-controls" => "mobile-menu", "aria-expanded" => "false", "data-action" => "click->dropdown#toggle click@window->dropdown#hide", "data-dropdown-enter-timeout" => "100", "data-dropdown-entering-class" => "ease-out duration-100", "data-dropdown-invisible-class" => "opacity-0 scale-95", "data-dropdown-leave-timeout" => "75", "data-dropdown-leaving-class" => "ease-in duration-75", "data-dropdown-visible-class" => "opacity-100 scale-100", type: "button"}
          %span.sr-only Open main menu
          /
            Icon when menu is closed.
            Heroicon name: outline/menu
            Menu open: "hidden", Menu closed: "block"
          %svg.block.h-6.w-6{"aria-hidden" => "true", fill: "none", stroke: "currentColor", "stroke-width" => "2", viewbox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg"}
            %path{d: "M4 6h16M4 12h16M4 18h16", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
          /
            Icon when menu is open.
            Heroicon name: outline/x
            Menu open: "block", Menu closed: "hidden"
          %svg.hidden.h-6.w-6{"aria-hidden" => "true", fill: "none", stroke: "currentColor", "stroke-width" => "2", viewbox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg"}
            %path{d: "M6 18L18 6M6 6l12 12", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
      .flex-1.flex.items-center.justify-center.sm:items-stretch.sm:justify-start.sm:justify-between
        = link_to root_path do
          .flex-shrink-0.flex.text-cyan-50.hover:text-cyan-300
            = inline_svg_tag("of_course_logo", desc: "Of Course: Course Guide", alt: "Of Course: Course Guide", class: "block  h-8 fill-current text-yellow-500  hover:text-yellow-400 group-hover:text-yellow-600 ")
            %span.hidden.sm:block.text-2xl.font-bold.align-bottom.align-text-bottom.mt-1.pl-1.whitespace-nowrap{"aria-hidden" => "true"} .
            %span.hidden.sm:block.text-yellow-500.text-lg.font-semibold.align-bottom.align-text-bottom.mt-2.pl-1.whitespace-nowrap.hover:text-2xl.ease-in{"aria-hidden" => "true"} g
            %span.hidden.sm:block.text-yellow-500.text-lg.font-semibold.align-bottom.align-text-bottom.mt-2.whitespace-nowrap.hover:text-2xl.ease-in{"aria-hidden" => "true"} u
            %span.hidden.sm:block.text-yellow-500.text-lg.font-semibold.align-bottom.align-text-bottom.mt-2.whitespace-nowrap.hover:text-2xl.ease-in{"aria-hidden" => "true"} i
            %span.hidden.sm:block.text-yellow-500.text-lg.font-semibold.align-bottom.align-text-bottom.mt-2.whitespace-nowrap.hover:text-2xl.ease-in{"aria-hidden" => "true"} d
            %span.hidden.sm:block.text-yellow-500.text-lg.font-semibold.align-bottom.align-text-bottom.mt-2.whitespace-nowrap.hover:text-2xl.ease-in{"aria-hidden" => "true"} e

        .hidden.sm:block.sm:ml-6
          .flex.space-x-4
            
            = link_to "Courses", courses_path, class: "text-cyan-50 hover:bg-gray-700 hover:text-cyan-300 px-2 py-2 rounded-md text-lg font-medium"
            / Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white"
            = link_to "About", about_path, class: "text-cyan-50 hover:bg-gray-700 hover:text-cyan-300 px-2 py-2 rounded-md text-lg font-medium"
            = link_to "Contact", contact_path, class: "text-cyan-50 hover:bg-gray-700 hover:text-cyan-300 px-2 py-2 rounded-md text-lg font-medium"
      .absolute.inset-y-0.right-0.flex.items-center.pr-2.sm:static.sm:inset-auto.sm:ml-6.sm:pr-0{"data-controller" => "dropdown"}
        / Profile dropdown
        - if current_user
          .ml-3.relative.z-10
            %div
              %button#user-menu-button.bg-gray-800.flex.text-sm.rounded-full.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-offset-gray-800.focus:ring-white{"aria-expanded" => "false", "aria-haspopup" => "true", "data-action" => "click->dropdown#toggle click@window->dropdown#hide", "data-dropdown-target" => "button", role: "button", type: "button"}
                %span.sr-only Open user menu
                %img.h-8.w-8.rounded-full{alt: current_user, src: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"}/
            /
              Dropdown menu, show/hide based on menu state.
              
              Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
              Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
            .origin-top-right.absolute.right-0.mt-2.w-48.rounded-md.shadow-lg.py-1.bg-white.ring-1.ring-black.ring-opacity-5.focus:outline-none{"aria-labelledby" => "user-menu-button", "aria-orientation" => "vertical", "data-dropdown-target" => "menu", role: "menu", tabindex: "-1"}
              / Active: "bg-gray-100", Not Active: ""
              .block.hover:text-slate-400.px-4.py-2.text-sm.text-gray-700
                = "Signed in as #{current_user.email}"
              = link_to "Your Profile", edit_user_registration_path, class: "block hover:text-slate-400 px-4 py-2 text-sm text-gray-700", role: "menuitem",  tabindex: "-1", id: "user-menu-item-0"
              = link_to "Settings", edit_user_registration_path, class: "block hover:text-slate-400 px-4 py-2 text-sm text-gray-700", role: "menuitem",  tabindex: "-1", id: "user-menu-item-1"
            
              = button_to "Sign out", destroy_user_session_path, method: :delete, class: "block hover:text-slate-400 px-4 py-2 text-sm text-gray-700 mt-2 -mb-1 hover:text-red-700 hover:bg-red-100 w-full text-start"
        - else
          = link_to "Sign in", new_user_session_path, class: "block hover:text-slate-400 px-4 py-2 text-sm text-cyan-50"
    / Mobile menu, show/hide based on menu state.
    #mobile-menu.sm:hidden
      .px-2.pt-2.pb-3.space-y-1{"data-dropdown-target" => "menu"}
        / Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white"
        = link_to "Home", root_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
        = link_to "About", about_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
        = link_to "Contact", contact_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = (t :sitename)
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    
    - if Rails.env.development?
      = javascript_include_tag "hotwire-livereload", defer: true
      
  %body{'data-environment' => Rails.env}
    = skip_links
    = render 'layouts/header_nav'
    = render 'layouts/utilities/tailwindcss_breakpoints' unless Rails.env.production?
    %main#main.container.mx-auto.mt-6.px-5.flex{class: controller.controller_name}
      = yield




    -# = render 'layouts/header_nav'

    -# = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"

    -# = skip_links
    -# = render 'layouts/utilities/tailwindcss_breakpoints' unless Rails.env.production?
    -# = render 'layouts/flash_messages'
    -# %main#main.container.mx-auto.mt-6.px-5.flex{class: controller.controller_name}
    -#   = yield